### ISSUE TITLE
initialize method will be called twice

### ISSUE THREAD

**Issue by ricoyu** [bcecchinato/spring-postinitialize#15] opened 2015-02-26 12:50 UTC
I've write my code like this:

Add:
<init:annotation-config/>
 into my existing applicationContext.xml,

and in 
    @Service
    public class BookFetchService {
        ....

        @PostInitialize
        public void fetchBooks() {
            ....
        }
    }

I add a breakpoint in this method, found it run twice.

**Comment by bcecchinato** [comment] 2015-02-26 20:04
Can you provide a more details on your project (the best would be to have access on your repo, or a tar of your sources so I can try to reproduce the problem) ?

**Comment by ricoyu** [comment] 2015-02-27 01:41
project host here:
https://github.com/ricoyu/ebook-lover

2015-02-27 4:04 GMT+08:00 Bastien Cecchinato <notifications@github.com>:

> Can you provide a more details on your project (the best would be to have
> access on your repo, or a tar of your sources so I can try to reproduce the
> problem) ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcecchinato/spring-postinitialize/issues/15#issuecomment-76258529>
> .
>



-- 
--------------------
Best Regards
RicoYu

**Comment by ricoyu** [comment] 2015-02-27 02:11
re-dent the project

2015-02-27 4:04 GMT+08:00 Bastien Cecchinato <notifications@github.com>:

> Can you provide a more details on your project (the best would be to have
> access on your repo, or a tar of your sources so I can try to reproduce the
> problem) ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcecchinato/spring-postinitialize/issues/15#issuecomment-76258529>
> .
>



-- 
--------------------
Best Regards
RicoYu

**Comment by bcecchinato** [comment] 2015-02-27 07:58
I haven't been able to reproduce the problem. If you still have the sources, can you put the following package fr.zebasto.spring.post.initialize in TRACE mode and give me the logs ?

Regards,

**Comment by ricoyu** [comment] 2015-02-27 09:00
2015-02-27 15:58 GMT+08:00 Bastien Cecchinato <notifications@github.com>:

> fr.zebasto.spring.post.initialize
>

​Bellow is piece of log:

2015-02-27 16:56:40 [ebook-info] DEBUG
org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor
L209-No @Scheduled annotations found on bean class: class
fr.zebasto.spring.post.initialize.bean.PostInitializeBeanProcessor

2015-02-27 16:56:42 [ebook-info] DEBUG
fr.zebasto.spring.post.initialize.bean.PostInitializeBeanProcessor
L144-Found 1 beans with max threads 32 and order 0
2015-02-27 16:56:42 [ebook-info] DEBUG
fr.zebasto.spring.post.initialize.bean.PostInitializeBeanProcessor$PostInitializingMethod
L225-Initializing bean named bookFetchService with method fetchBooks
​



-- 
--------------------
Best Regards
RicoYu

**Comment by bcecchinato** [comment] 2015-02-27 09:29
Regarding the logs, the method fetchBooks is initialized only once.
The following trace *Found 1 beans with max threads 32 and order 0* means that only one eligible method has been found. Then *Initializing bean named bookFetchService with method fetchBooks* means that we launch the method.

If you don't have a second line, this means that the method is execute else where.
Maybe this is because of the @Schedule annotation. Have you tried to use only the @PostInitialize annotation so you can check if the method still run twice ?

Regards,

**Comment by ricoyu** [comment] 2015-02-27 11:31
Have nothing to do with @Schedule, I remove this annotation it still runs
twice.

Found that
fr.zebasto.spring.post.initialize.bean.PostInitializeBeanProcessor.onApplicationEvent(ContextRefreshedEvent)
been executed twice, is this due to there is two applicationContext?
one for root applicationContext initialized
by org.springframework.web.context.ContextLoaderListener,
one for org.springframework.web.servlet.DispatcherServlet

2015-02-27 17:29 GMT+08:00 Bastien Cecchinato <notifications@github.com>:

> Regarding the logs, the method fetchBooks is initialized only once.
> The following trace *Found 1 beans with max threads 32 and order 0* means
> that only one eligible method has been found. Then *Initializing bean
> named bookFetchService with method fetchBooks* means that we launch the
> method.
>
> If you don't have a second line, this means that the method is execute
> else where.
> Maybe this is because of the @Schedule <https://github.com/Schedule>
> annotation. Have you tried to use only the @PostInitialize annotation so
> you can check if the method still run twice ?
>
> Regards,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcecchinato/spring-postinitialize/issues/15#issuecomment-76362318>
> .
>



-- 
--------------------
Best Regards
RicoYu

**Comment by bcecchinato** [comment] 2015-02-27 12:02
Yes I could be the reason. Are you using the <init:annotation-config/> in both context ?
Anyway, I'll make some tests with two or more contexts.

**Comment by bcecchinato** [comment] 2015-03-04 12:11
I did some tests, there a case indeed when your application is split in multiple contexts. Both root and child contexts are raising the ContextRefreshedEvent. I'll try to find a way to start the initialization when all contexts are ready.

Regards,

**Comment by ricoyu** [comment] 2015-03-04 12:32
yep, coincidence with my last found. I found another problem when I try to
deploy my project in linux environment, will discuss with u later

2015-03-04 20:11 GMT+08:00 Bastien Cecchinato <notifications@github.com>:

> I did some tests, there a case indeed when your application is split in
> multiple contexts. Both root and child contexts are raising the
> ContextRefreshedEvent. I'll try to find a way to start the initialization
> when all contexts are ready.
>
> Regards,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcecchinato/spring-postinitialize/issues/15#issuecomment-77147252>
> .
>



-- 
--------------------
Best Regards
RicoYu

**Comment by bcecchinato** [comment] 2015-03-04 15:59
This is fixed by adding a check on the application context that is attached to the event and the local application autowired by spring (as discussed by with spring staff on https://jira.spring.io/browse/SPR-12781). Regards.

I'll make some tests to check if it's now ok before releasing.
Regards,

**Comment by bcecchinato** [comment] 2015-03-06 07:28
Using the application context is not enough, however I've managed to fix the problem using the second solution provided by spring team.

**Closed** 2015-03-06 07:29 UTC
Labels: bug, question
